module.exports = {
  INDEX: 'GET /administrator',
  CLIENT_JS: 'GET /administrator/client.js',
  MODEL_COUNT: 'POST /administrator/model-count',
  MODEL_CREATE: 'POST /administrator/model-create',
  MODEL_DELETE: 'DELETE /administrator/model-delete/:id',
  MODEL_UPDATE: 'PUT /administrator/model-update/:id',
  MODEL_SEARCH: 'POST /administrator/model-search',
  MODEL_SEARCH_ALL: 'GET /administrator/model-search-all',
  MODELS_COUNT: 'GET /administrator/all-models-count',
  LOGIN: 'POST /administrator/login',
  UPLOAD: 'POST /administrator/model-upload-asset',
  MODELS_ASSETS: 'POST /administrator/models-assets',
  VIEW_CONTENT: 'POST /administrator/view-content',
  REPORT_CONTENT: 'GET /administrator/report-content',
  ASSET: 'GET /administrator/crud-asset/:hash',
};
